### ISSUE TITLE
Unable to deploy using 'stable' repo

### ISSUE THREAD

**Issue by junaid-ali** [Orange-OpenSource/opnfv-cloudify-clearwater#23]
If we use `stable` repo in inputs file, bind node installation fails with the following error: 
```
2018-11-13 13:02:05.573  CFY <step-test-1> [establish] Task failed 'script_runner.tasks.run' -> Failed setting state to reload: Command 'sudo service bind9 reload' executed with an error.
code: 1
error: rndc: connect failed: 127.0.0.1#953: connection refused
output:  * Reloading domain name service... bind9
   ...fail!
Traceback (most recent call last):
  File "/home/ubuntu/bind_host_opbsfz/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 669, in main
    payload = handler.handle()
  File "/home/ubuntu/bind_host_opbsfz/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 411, in handle
    result = self.func(*self.args, **kwargs)
  File "/home/ubuntu/bind_host_opbsfz/env/lib/python2.7/site-packages/script_runner/tasks.py", line 80, in run
    script_result = process_execution(script_func, script_path, ctx, process)
  File "/home/ubuntu/bind_host_opbsfz/env/lib/python2.7/site-packages/script_runner/tasks.py", line 156, in process_execution
    script_func(script_path, ctx, process)
  File "/home/ubuntu/bind_host_opbsfz/env/lib/python2.7/site-packages/script_runner/tasks.py", line 332, in eval_script
    execfile(script_path, eval_globals)
  File "/tmp/3Y2JV/bind.py", line 262, in <module>
    _main()
  File "/tmp/3Y2JV/bind.py", line 258, in _main
    globals()[function](*args, **kwargs)
  File "/tmp/3Y2JV/bind.py", line 195, in add_backend
    'public_address' : public_ip
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/tmp/3Y2JV/bind.py", line 217, in _backends_update
    configure(subject=ctx.target)
  File "/tmp/3Y2JV/bind.py", line 105, in configure
    reload()
  File "/tmp/3Y2JV/bind.py", line 237, in reload
    _service('reload')
  File "/tmp/3Y2JV/bind.py", line 242, in _service
    error_message='Failed setting state to {0}'.format(state))
  File "/tmp/3Y2JV/bind.py", line 250, in _run
    raise exceptions.NonRecoverableError('{0}: {1}'.format(error_message, e))
NonRecoverableError: Failed setting state to reload: Command 'sudo service bind9 reload' executed with an error.
code: 1
error: rndc: connect failed: 127.0.0.1#953: connection refused
output:  * Reloading domain name service... bind9
   ...fail!
```

The issue appears to be due to removal of 'bind9' package by the clearwater-managment package which gets installed on bind node.
If I try to install bind9 manually on bind node:
```$ sudo apt-get install bind9```
The output looks like following:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  dnsmasq dnsmasq-base inotify-tools iotop libinotifytools0 libmnl0
  libnetfilter-conntrack3 libopts25 libpgm-5.1-0 libsensors4 libzmq3 ntp
  python-chardet-whl python-colorama python-colorama-whl python-distlib
  python-distlib-whl python-html5lib python-html5lib-whl python-jsonschema
  python-mock python-pip python-pip-whl python-requests-whl
  python-setuptools-whl python-six-whl python-urllib3-whl python-virtualenv
  python-wheel python3-pkg-resources realpath sysstat
Use 'apt-get autoremove' to remove them.
Suggested packages:
  bind9-doc
The following packages will be REMOVED:
  clearwater-cluster-manager clearwater-config-manager
  clearwater-diags-monitor clearwater-etcd clearwater-infrastructure
  clearwater-log-cleanup clearwater-management clearwater-monit
  clearwater-queue-manager
The following NEW packages will be installed:
  bind9
0 upgraded, 1 newly installed, 9 to remove and 0 not upgraded.
Need to get 0 B/287 kB of archives.
After this operation, 114 MB disk space will be freed.
Do you want to continue? [Y/n]
```
The bind9 installation tries to remove the clearwater packages and if we try to install clearwater-management package, it tries to remove bind9.

Clearwater package versions at stable repo:
```$ dpkg -l | grep clearwater
ii  clearwater-cluster-manager       1.0-180413.163540                          all          Cluster manager for Clearwater
ii  clearwater-config-manager        1.0-180413.163540                          all          Configuration manager for Clearwater
ii  clearwater-diags-monitor         1.0-180328.114312                          all          Diagnostics monitor and bundler for all Clearwater servers
ii  clearwater-etcd                  1.0-180328.115321                          all          etcd configured for Clearwater
ii  clearwater-infrastructure        1.0-180328.114312                          amd64        Common infrastructure for all Clearwater servers
ii  clearwater-log-cleanup           1.0-180328.114312                          all          Script to prevent sprout/bono log files from growing too large
ii  clearwater-management            1.0-180413.163540                          all          Meta-package for installing all Clearwater management services
ii  clearwater-monit                 5.18-180322.170159                         amd64        utility for monitoring and managing daemons or similar programs
ii  clearwater-queue-manager         1.0-180413.163540                          all          Queue manager for Clearwater
```

Bind9 version:
```
$ dpkg -l | grep bind
rc  bind9                            1:9.9.5.dfsg-3ubuntu0.18                   amd64        Internet Domain Name Server
ii  bind9-host                       1:9.9.5.dfsg-3ubuntu0.18                   amd64        Version of 'host' bundled with BIND 9.X
ii  bind9utils                       1:9.9.5.dfsg-3ubuntu0.18                   amd64        Utilities for BIND
```

**Comment by collivier** [comment]
This repo is mostly used by Functest and works very well in that context even vs latest OpenStack release (master)
Functest leverages on the gambia branch rather than stable here:
- https://git.opnfv.org/functest/tree/docker/vnf/Dockerfile#n5
- https://build.opnfv.org/ci/job/functest-opnfv-functest-vnf-latest-cloudify_ims-run/321/console
- https://wiki.opnfv.org/pages/viewpage.action?pageId=56295675

I would encourage you to use Functest or at least to follow the same branch choices.
I may clean the former branches as they are misleading here.
